{% set version = "1.0" %}
{% set build = 0 %}

package:
  name: radioconda_console_shortcut
  version: {{ version }}

build:
  number: {{ build }}
  skip: True  # [not win]

test:
  commands:
    - if not exist %PREFIX%\\Menu\\console_shortcut.json exit 1
    - if not exist %PREFIX%\\Menu\\console_shortcut.ico exit

about:
  home: https://github.com/ryanvolz/radioconda
  summary: Command prompt shortcut for Windows with base environment activated
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ryanvolz
